[package]
name = "sandstorm"
description = "SHARP compatible Cairo prover"
authors = ["Andrew Milson <andrew.j.milson@gmail.com>"]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["layouts", "binary"]

[features]
default = [ ]
asm = [ "ministark/asm" ]
gpu = [ "ministark/gpu" ]
parallel = [ "dep:rayon", "ministark/parallel" ]

[dependencies]
layouts = { path = "./layouts", package = "sandstorm-layouts" }
binary = { path = "./binary", package = "sandstorm-binary" }
ministark-gpu = { version = "0.1", git = "https://github.com/andrewmilson/ministark" }
ministark = { git = "https://github.com/andrewmilson/ministark" }
ark-poly = { git = "https://github.com/andrewmilson/algebra", branch = "vec-allocator" }
ark-std = "0.4"
ark-ff = "0.4"
ark-serialize = "0.4"
structopt = "0.3"
serde_json = "1.0"
num-traits = "0.2"
strum = { version = "0.21", features = ["derive"] }
pollster = "0.2"
rayon = { version = "1.5", optional = true }

# taken from https://github.com/recmo/uint
# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true

# TODO: remove
[dev-dependencies]
num-bigint = "0.4"
ark-ec = "0.4"