[package]
name = "sandstorm"
description = "SHARP compatible Cairo prover"
authors = ["Andrew Milson <andrew.j.milson@gmail.com>"]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["layouts"]

[features]
default = [ ]
asm = [ "ministark/asm" ]
gpu = [ "ministark/gpu" ]
parallel = [ "dep:rayon", "ministark/parallel" ]

[dependencies]
layouts = { path = "./layouts" }
gpu-poly = { path = "../ministark-mirror/gpu-poly" }
ministark = { path = "../ministark-mirror" }
# ministark = { git = "https://github.com/andrewmilson/ministark" }
# gpu-poly = { git = "https://github.com/andrewmilson/ministark" }
ark-poly = { git = "https://github.com/andrewmilson/algebra", branch = "vec-allocator" }
ark-std = "0.4.0"
ark-ff = "0.4.0"
ark-serialize = "0.4.0"
structopt = "0.3.26"
bincode = "1.2.1"
num-bigint = "0.4.3"
ruint = { version = "1.7.0", features = [ "serde", "num-bigint" ] }
serde = "1.0.147"
serde_json = "1.0.89"
strum = "0.24.1"
num-traits = "0.2.15"
pollster = "0.2.4"
rayon = { version = "1.5.3", optional = true }

# TODO: can remove these
# [build-dependencies]
# ministark = { path = "../ministark-mirror" }
# codegen = { path = "./codegen" }
# proc-macro2 = "1.0"
# anyhow = "1.0.70"
# layouts = { path = "./layouts" }
# ark-poly = { git = "https://github.com/andrewmilson/algebra", branch = "vec-allocator" }

# taken from https://github.com/recmo/uint
# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true